<?php
require_once("backend/controllers/PhoneBookController.php");

if (isset($_POST["Save"])) {
    $controller = new PhoneBookController();
    $controller-> ajaxInsert();
}
$controller = new PhoneBookController();

$data = $controller->getProducts();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container px-3">
    <form id="product_form" action="" method="post">
        <div class="row py-5 mt-3">
            <h3 class="col-6 justify-content-md-start">Product Add</h3>
            <div class="col-6 d-grid gap-2 d-md-flex">
                <input name="Save" type="submit" value="Save" class="btn btn-success">
                <a href="/" class="btn btn-danger">Cancel</a>
            </div>
        </div>
        <hr>
        <div class="col-sm-3 mt-3">
            <div class="row ">
                <div class="col-md-4">
                    <label for="number" class="form-label ">Phone number</label>
                </div>
                <div class="col-md-8 ">
                    <input name="number" type="text" class="form-control" id="number" autocomplete="off">
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-3">
            <div class="row">
                <div class="col-md-4">
                    <label for="name" class="form-label">Name</label>
                </div>
                <div class="col-md-8">
                    <input name="name" type="text" class="form-control" id="name" autocomplete="off">
                </div>

            </div>
        </div>

    </form>
</div>
<script src="node_modules/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="script.js"></script>
</body>
</html>
