<?php
require_once("backend/PhoneBookController.php");
require_once("backend/PhoneBookModel.php");
$controller = new PhoneBookController();
$products = $controller->index();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <!--    <link rel="stylesheet" href="style.css">-->
    <meta charset="UTF-8">
    <title>Product List</title>
</head>
<body>
<div class="container px-3">
    <div class="py-3 mx-3 justify-content-md-center">
    <h3 class="col-6 justify-content-md-start">Phone Book</h3>
    </div>
    <p>
<div>
    <form id="insert-form" action="" method="post">
        <div class="row">
            <div class="row py-5 mx-5">
        <div class="col">
            <div class="row ">
                <div class="col-md-4">
                    <label for="phone" class="form-label">Phone number</label>
                </div>
                <div class="col-md-8 ">
                    <input name="phone" type="text" class="form-control" id="phone" autocomplete="off">
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col-md-4">
                    <label for="surname" class="form-label">Name</label>
                </div>
                <div class="col-md-8">
                    <input name="surname" type="text" class="form-control" id="surname" autocomplete="off">
                </div>

            </div>
        </div>
        <div class="col">
            <input name="Save" type="submit" value="Save" class="btn btn-success">
        </div>
        </div>
    </form>

</div>




        <div class="slider multiple-items">
            <table class="table table-striped">
                <thead>
                <tr>

                    <th scope="col">Surname</th>
                    <th scope="col">Phone</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($products as $product) { ?>

                    <tr>
                        <td><p><label>
                                    <input type="text" value="<?= $product->getSurname() ?>" disabled>
                                </label></p></td>
                        <td><p><label>
                                    <input type="text" value="<?= $product->getPhone() ?>" disabled>
                                </label></p></td>
                        <td><p><input name="Change" type="submit" value="Change" class="btn btn-success" ></p></td>
                        <td><p><input name="Save-Change" type="submit" value="Save-Change" class="btn btn-success" disabled></p></td>
                        <td><p><input name="Delete" type="submit" value="Delete" class="btn btn-success" ></p></td>
                        <td <?= $product->getId(); ?>></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <p>

    </div>
</div>



<script src="node_modules/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="script.js"></script>
</body>
</html>
